### PR TITLE
Add iOS support

### PR DESCRIPTION
**Pull request by shekohex**
This adds iOS support, it treats iOS targets as macOS (they act the same).

I did the same for [`sysinfo`](https://github.com/GuillaumeGomez/sysinfo/pull/343) crate.

### CODE REVIEW

**Comment by ohadravid** [comment]
LGTM, can you confirm this actually works on iOS (vs just compiling correctly)?

**Comment by shekohex** [comment]
iOS applications build statically so mostly if it compiles it should contain all symbols and code required for it to work correctly.

**Comment by ohadravid** [comment]
I mean, does it *run* correctly on iOS?
Since I don't have an iOS test env, I can't check it myself. 
If you are unable to test it as well that's fine, but it would be better to know that it does what it's supposed to do before merging 😄

**Comment by shekohex** [comment]
We at @sunshine-protocol building native apps using Flutter and Rust, one of our projects [sunshine-identity-ui](https://github.com/sunshine-protocol/sunshine-identity-ui) has a dependency that uses this crate, but it fails to compile in iOS, I tested with current branch (by patching crates in cargo.toml file).

> As of writing this comment we still have an issue get our Rust code to compile on iOS because of sysinfo, although we patched the upstream sysinfo crate the dependency that uses it still uses an old version which we also opened a PR there to solve it.

So it's okay to hold that PR for now, we could test by using a git url + branch and if it worked correctly I will inform you 😊

Thanks.

**Comment by dvc94ch** [comment]
Linux/Android are similar enough that you should be able to add Android too in the same way

**Comment by shekohex** [comment]
Hey @ohadravid we tested the app on iOS and it builds and runs with no issues see https://github.com/sunshine-protocol/sunshine-identity-ui/issues/4 
also, the `sysinfo` crate works too.

So I guess you could merge this now 😄

**Pull request merged**
